added perimeter and circumference setters and tests
glotzerlab/coxeter pull request #102
Opened 2020-10-08 18:43 UTC by Tobias-Dwyer

added perimeter and circumference getter and setter tests and the ability to set the circumference and perimeter of a circle

## Description

simple, see summary
## Motivation and Context

consistency between what we can get and set

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2020-10-08 18:50 UTC, vyasr requested changes

2020-10-08 18:50 UTC, vyasr commented on coxeter/shape_classes/circle.py
> +
To be consistent with the getter, can you just call the perimeter setter in the circumference setter?

2020-10-08 18:50 UTC, vyasr commented on coxeter/shape_classes/circle.py
> +        self._radius = value / (2 * np.pi)
We need to do some amount of validation of the input here. The division will automatically fail if users pass something completely bogus like `circle.perimeter = 'hello tobias'`, but if you set a perimeter <= 0 you won't currently warn the user that they're doing something invalid. I would raise an error in such cases.

2020-10-08 20:02 UTC, bdice commented on tests/test_circle.py
> +def test_perimeter_setter(perimeter):
Please also test the circumference setter. (The circumference property getter is tested in `test_perimeter`.)

2020-10-09 14:36 UTC, Tobias-Dwyer commented on coxeter/shape_classes/circle.py
> +
Yep!

2020-10-09 14:37 UTC, Tobias-Dwyer commented on coxeter/shape_classes/circle.py
> +        self._radius = value / (2 * np.pi)
added checks.

2020-10-09 14:38 UTC, Tobias-Dwyer commented on tests/test_circle.py
> +def test_perimeter_setter(perimeter):
tested it!

2020-10-09 16:09 UTC, bdice requested changes

2020-10-09 16:09 UTC, bdice commented on coxeter/shape_classes/circle.py
> +            print("Area must be greater than zero.")
This needs to raise a ValueError. Same below.

2020-10-09 16:09 UTC, bdice commented on coxeter/shape_classes/circle.py
> +            self._radius = np.sqrt(value / np.pi)
This should use the public radius property setter so that any additional validation or cache invalidation logic is triggered. Same below.

2020-10-09 17:39 UTC, Tobias-Dwyer commented on coxeter/shape_classes/circle.py
> +            print("Area must be greater than zero.")
learned about errors more and added it :D

2020-10-09 17:39 UTC, Tobias-Dwyer commented on coxeter/shape_classes/circle.py
> +            self._radius = np.sqrt(value / np.pi)
added it :D

2020-10-09 20:40 UTC, bdice approved these changes

2020-10-12 14:49 UTC, vyasr requested changes
Couple of minor changes requested. I'm going to apply the ones that were suggested, that just leaves one outstanding request that you need to do.

2020-10-12 14:49 UTC, vyasr commented on coxeter/shape_classes/circle.py
> +            raise ValueError("Radius must be greater than zero.")
```suggestion
        self.radius = radius
```

2020-10-12 14:49 UTC, vyasr commented on coxeter/shape_classes/convex_spheropolyhedron.py
> +            raise ValueError("Radius must be greater than zero.")
```suggestion
        self.radius = radius
```

2020-10-12 14:49 UTC, vyasr commented on coxeter/shape_classes/convex_spheropolyhedron.py
> +            raise ValueError("Radius must be greater than zero.")
```suggestion
            raise ValueError("Rounding radius must be greater than or equal to zero.")
```

2020-10-12 14:49 UTC, vyasr commented on tests/test_circle.py
> +    assert circle.radius == (perimeter + 1) / (2 * np.pi)
While the effect of setting circumference/perimeter is to change the radius, it's a bit odd not to also check what you get from the circumference and perimeter properties once you set them. Could you also add checks that `circle.perimeter == perimeter` (and for circumference)?

2020-10-12 16:43 UTC, vyasr approved these changes

2020-10-12 16:43 UTC, merged