Enable doctests
glotzerlab/coxeter pull request #109
Opened 2020-10-09 02:30 UTC by bdice

## Description
This PR enables doctests in pytest, so they will run during continuous integration.

To make doctests work, I enabled two options.

`ELLIPSIS` allows non-deterministic results to be ignored by putting `...`.
`NORMALIZE_WHITESPACE` allows lines to be wrapped for flake8 even if the output does not contain newlines.

I also reformatted the examples sections so they render better. Resolves #104.

## Motivation and Context
Doctests ensure that the code examples continue to work as the package is changed.

## Types of Changes

- [x] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2020-10-09 02:43 UTC, vyasr requested changes
While you're doing this, can you also delete all the extra examples as mentioned in #104? For instance, it's enough to do `circumcircle = square.circumcircle` without asking for `circumcircle.radius` etc in the example. Other than that it looks good!

2020-10-09 02:43 UTC, vyasr commented on .circleci/config.yml
> +            python -m pytest --doctest-modules
```suggestion
            python -m pytest
```
This change is redundant now.

2020-10-09 02:43 UTC, vyasr commented on setup.cfg
> +addopts = --doctest-modules -p coxeter.__doctest_fixtures
This doesn't have to be done in this PR, but in hindsight I'm wondering whether doing everything in terms of the top-level coxeter namespace is really preferable. Should we just use the local names everywhere (e.g. `circle = Circle(...)` instead of `circle = coxeter...`)? If so, then we could get rid of the extra fixtures entirely.

2020-10-09 02:47 UTC, bdice commented on setup.cfg
> +addopts = --doctest-modules -p coxeter.__doctest_fixtures
I like having full names in the code examples, because they're easier to copy-paste. I support leaving it as-is.

2020-10-12 16:48 UTC, vyasr approved these changes
Thanks!

2020-10-12 16:49 UTC, merged