Add to_plato_scene feature.
glotzerlab/coxeter pull request #132
Opened 2020-12-19 03:20 UTC by bdice

## Description

## Motivation and Context

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2020-12-19 03:58 UTC, bdice commented
This PR also fixes a docs issue: https://github.com/executablebooks/jupyter-book/issues/1137

2020-12-19 04:15 UTC, bdice commented on coxeter/families/tabulated_shape_family.py
> +shape schema <gsd:shapes>`, which defines how to translates dictionaries with
This is an unrelated improvement to Sphinx reference syntax. I wanted to namespace this so that the GSD "shapes" reference doesn't conflict with the subpackage name "shapes" of coxeter, should we choose to add a sphinx reference for that. (I didn't know how to use sphinx reference namespaces until recently.)

2020-12-24 01:41 UTC, vyasr commented
One possible roadblock to replacing the `plot` method with `to_plato_scene` (discussed offline with @bdice) is that `plot` allows users to integrate a shape directly into a matplotlib figure, which is much easier and more familiar for most users. We should look into whether the plato matplotlib backend has a way to accomplish this, perhaps by constructing a scene that points to an existing figure/axis.

2021-02-01 18:13 UTC, vyasr commented
> One possible roadblock to replacing the `plot` method with `to_plato_scene` (discussed offline with @bdice) is that `plot` allows users to integrate a shape directly into a matplotlib figure, which is much easier and more familiar for most users. We should look into whether the plato matplotlib backend has a way to accomplish this, perhaps by constructing a scene that points to an existing figure/axis.

In hindsight, I think all that's required here is to add `ax, fig` to the signature to be forwarded to the scene constructor so that users can treat use this solely via matplotlib. Also maybe a `render=True` kwarg so that it automatically draws on the axis. Users who actually want to interact via plato APIs can then pass `render=False` to get the plato scene and work with it directly if they want.

2021-02-03 23:06 UTC, bdice commented
Discussed with @vyasr -- we'll just allow forwarded `**kwargs` to the Scene constructor if `scene is None`.

2021-02-04 17:05 UTC, bdice commented
@glotzerlab/coxeter-maintainers I updated the PDF attached at the top of this PR description with an example of matplotlib scenes, per @vyasr's request. Should I commit that Jupyter notebook with example scenes to the `tests/` directory?

2021-02-04 17:45 UTC, bdice commented
@glotzerlab/coxeter-maintainers This is finished and ready for review. I verified that the new tests of using plato to draw all supported shapes with matplotlib pass on CI, and they are skipped if matplotlib or plato are unavailable.

2021-02-07 00:12 UTC, vyasr requested changes
Looks good. I've requested a few things, but depending on what you think you may not have to do anything for most of them. Ping me once you've addressed them one way or another.

2021-02-07 00:12 UTC, vyasr commented on coxeter/shapes/base_classes.py
> +        raise NotImplementedError("This shape does not have a plato primitive.")
I'm anticipating that most people will be unfamiliar with plato, so perhaps a more informative error would just be to indicate that plotting is not supported (which can always be forwarded to devs who do know that this means that the `_plato_primitive` method must be implemented.
```suggestion
        raise NotImplementedError("This shape does not support plotting.")
```

2021-02-07 00:12 UTC, vyasr commented on coxeter/shapes/base_classes.py
> +    def to_plato_scene(self, backend=None, scene=None, **scene_kwargs):
Can we use matplotlib as a default backend? I realize that not every shape is supported, but the vast majority are (I think it's just spheropolyhedra that are not?) and I would expect matplotlib to be the default choice for most people. We can document that this may not be supported for all shapes, and perhaps catch the relevant exceptions below if we know what plato raises when an invalid primitive is attempted.

2021-02-07 00:12 UTC, vyasr commented on coxeter/shapes/convex_spheropolygon.py
> +        )[0]
The validity of this is impacted by #149, right? Will polygons not in the plane be plottable?

2021-02-07 00:12 UTC, vyasr commented on coxeter/shapes/polygon.py
> +        verts = _align_points_by_normal(self.normal, self.vertices - self.center)[0]
Same question as for spheropolygons, how does #149 impact this?

2021-02-07 00:12 UTC, vyasr commented on coxeter/shapes/polyhedron.py
> +            colors=np.array([[0.5, 0.5, 0.5, 1]] * len(self.vertices)),
This makes me wonder, should we support primitive kwargs in addition to scene kwargs so that the user can specify things like the color? I'm also fine with punting on this, just thought I'd ask.

2021-02-07 00:12 UTC, vyasr commented on tests/test_plato.py
> +import coxeter
This spacing seems strange, why is there a newline between tempfile and pytest?

2021-02-07 00:12 UTC, vyasr commented on tests/test_plato.py
> +import coxeter
Tests pass, so it's fine, I'm just confused.

2021-02-07 00:17 UTC, bdice commented on tests/test_plato.py
> +import coxeter
isort sections: `FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER` [(source)](https://pycqa.github.io/isort/#custom-sections-and-ordering)

`tempfile` is STDLIB
`pytest` is THIRDPARTY
`coxeter` is FIRSTPARTY.

2021-02-07 00:18 UTC, bdice commented on coxeter/shapes/polyhedron.py
> +            colors=np.array([[0.5, 0.5, 0.5, 1]] * len(self.vertices)),
Good idea, I considered it but I didn't want to bother with that yet. I vote to punt on this.

2021-02-07 00:18 UTC, bdice commented on coxeter/shapes/polygon.py
> +        verts = _align_points_by_normal(self.normal, self.vertices - self.center)[0]
This code will need to be updated, yes. It will only support in-plane shapes (because that's what plato supports).

2021-02-07 00:18 UTC, bdice commented on coxeter/shapes/convex_spheropolygon.py
> +        )[0]
This code will need to be updated, yes. It will only support in-plane shapes (because that's what plato supports).

2021-02-07 00:20 UTC, bdice commented on coxeter/shapes/base_classes.py
> +    def to_plato_scene(self, backend=None, scene=None, **scene_kwargs):
Sure, we can set a default backend. I don't want to handle catching/re-raising exceptions here. I would prefer to just make a note in the docs and let users handle that.

2021-02-07 00:23 UTC, bdice commented on coxeter/shapes/base_classes.py
> +        raise NotImplementedError("This shape does not have a plato primitive.")
1. This is only raised when users call a method named `to_plato_scene`, so I think the existing error message here is more descriptive/helpful. Users should not be surprised to see the name "plato."
2. I think "does not support plotting" falsely indicates a deficiency in coxeter rather than the external library (plato) that coxeter is calling.

2021-02-07 00:23 UTC, bdice commented on coxeter/shapes/base_classes.py
> +                in which case the ``scene`` argument must be provided.
Yes, that's a great idea. I will add docs and links to indicate that the matrix of backends/primitives is not fully populated and where to get more info.

2021-02-07 00:24 UTC, vyasr commented on tests/test_plato.py
> +import coxeter
I forgot that tempfile and pytest are separate groups, thanks.

2021-02-07 00:25 UTC, vyasr commented on coxeter/shapes/polyhedron.py
> +            colors=np.array([[0.5, 0.5, 0.5, 1]] * len(self.vertices)),
That's fine with me, but if we're punting (rather than making this as `wontfix`) should we instead make `to_plato_scene` accept a dict of `scene_kwargs` rather than forward all `**scene_kwargs` so that we have the flexibility in the future to add a `primitive_kwargs` dict argument or similar?

2021-02-07 00:25 UTC, vyasr commented on coxeter/shapes/polygon.py
> +        verts = _align_points_by_normal(self.normal, self.vertices - self.center)[0]
Do you just want to merge this as is for now, then deal with this again later?

2021-02-07 00:25 UTC, vyasr commented on coxeter/shapes/base_classes.py
> +    def to_plato_scene(self, backend=None, scene=None, **scene_kwargs):
That seems like a reasonable compromise to me.

2021-02-07 00:28 UTC, vyasr commented on coxeter/shapes/base_classes.py
> +        raise NotImplementedError("This shape does not have a plato primitive.")
Yes, that's a good point. It does make me wonder whether we should alias `to_plato_scene` with something like `plot` to make it easier for unfamiliar users who might not know what to look for if they don't find something that is actually called `plot`. I'm OK doing that in a separate PR if you'd like to just be done with this one for now, but I do think that would be useful for anyone (especially outside our group) who tries to use it.

2021-03-30 04:35 UTC, bdice commented on coxeter/shapes/base_classes.py
> +            backend = importlib.import_module("plato.draw.{}".format(backend))
Note to self: this shouldn't be executed if the scene already exists and has a backend.

2021-06-14 00:24 UTC, bdice commented on coxeter/shapes/base_classes.py
> +                in which case the ``scene`` argument must be provided.
Resolved in d9c74f7b386edc783b06464e592b3375fa2ec39e.

2021-06-14 00:30 UTC, bdice commented on coxeter/shapes/base_classes.py
> +        raise NotImplementedError("This shape does not have a plato primitive.")
I think we can leave it as `to_plato_scene` for now. I think this is a case where explicit is better than implicit. Plotting is very generic, but this functionality is fairly specific to plato. I could see `plot` being an alias for creating a matplotlib figure, for instance.

2021-06-14 00:33 UTC, bdice commented on coxeter/shapes/base_classes.py
> +    def to_plato_scene(self, backend=None, scene=None, **scene_kwargs):
Default backend set to matplotlib in 6f314bd31c83895fc6bbe5e3502f08192343b6f5.

2021-06-14 00:36 UTC, bdice commented on coxeter/shapes/polygon.py
> +        verts = _align_points_by_normal(self.normal, self.vertices - self.center)[0]
I agree we should merge this PR and then focus on resolving the conflict with #149 afterward. I created a note on #149 to handle this.

2021-06-14 00:37 UTC, bdice commented on coxeter/shapes/polyhedron.py
> +            colors=np.array([[0.5, 0.5, 0.5, 1]] * len(self.vertices)),
Changed from `**scene_kwargs` to `scene_kwargs` in a3e63e5f0a3c2270e918b7ec841630a980cf8981.

2021-06-14 01:04 UTC, bdice commented
@vyasr @Tobias-Dwyer This is ready for another round of review. I will need to make some changes to #149 after this PR is merged and have noted those changes in the description of #149.

2021-06-15 18:15 UTC, Tobias-Dwyer commented on coxeter/shape_getters.py
> +    those can be inferred from simulation boxes. To address this ambiguity,
Change 'those' to 'the dimension of the shape' to eliminate some ambiguity in the writing.

2021-06-15 18:27 UTC, Tobias-Dwyer reviewed
just a small comment to disambiguate the language of the documentation and you should be good!

2021-06-15 18:33 UTC, bdice commented on coxeter/shape_getters.py
> +    those can be inferred from simulation boxes. To address this ambiguity,
Good idea. Done!

2021-06-17 06:27 UTC, vyasr commented
I still owe a review here, just letting you know that it's on my list.

2021-06-24 19:33 UTC, vyasr approved these changes
LGTM, thanks!

2021-06-24 19:33 UTC, vyasr commented on coxeter/shape_getters.py
> +    can be used to disambiguate explicitly between these two cases.
```suggestion
    circles) and ellipsoids (vs. ellipses) because in context the
    dimensionality of those shapes can be inferred from simulation boxes. To
    address this ambiguity, this function accepts a ``dimensions`` parameter
    that can be used to disambiguate explicitly between these two cases.
```

2021-06-24 19:33 UTC, vyasr commented on coxeter/shapes/base_classes.py
> +            `NotImplementedError`:
```suggestion
            NotImplementedError:
```

2021-06-24 19:33 UTC, vyasr commented on coxeter/shapes/base_classes.py
> +            `AttributeError`:
```suggestion
            AttributeError:
```

2021-06-24 19:44 UTC, merged