Rewrite tests to explicit reuse fixtures to avoid hypothesis errors.
glotzerlab/coxeter pull request #138
Opened 2021-01-12 21:11 UTC by vyasr

## Description

This PR rewrites test that were implicitly reusing pytest fixtures to make this reuse explicit. I added a changelog entry since this may be important for others to track the reason for the failures.

## Motivation and Context

#122 added various tests that reuse pytest fixtures in hypothesis tests. Those tests would pass with warnings in older versions of hypothesis, but the [recent release of hypothesis 6.0.0 makes this an error](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-0-0). These changes will avoid problems in the future.

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2021-01-12 22:15 UTC, bdice commented
@Tobias-Dwyer Just so you're aware as a maintainer, we usually catch problems introduced by testing dependency upgrades by using a tool called dependabot for freud and signac. It creates PRs like [this one](https://github.com/glotzerlab/freud/pull/710). It could be useful to set up for coxeter. We would pin all testing dependencies in `requirements-testing.txt` and let dependabot upgrade that on a monthly basis.

2021-01-12 22:21 UTC, bdice requested changes
@vyasr We should just use
```python
@pytest.fixture(scope="module")
```
instead.

2021-01-12 22:35 UTC, vyasr commented
@bdice why? While that makes the error go away, that assumes that any change in the fixture from one test is safe to persist to another, right? That _might_ be true, but I don't see why you would want to assume that when so many tests modify the fixture. Even if that's currently true, it would be easy to see adding one future tests that makes a nontrivial modification (e.g. changing the vertices of a shape since we've discussed making vertices settable) in a way that violates assumptions in another test.

2021-01-12 23:11 UTC, bdice commented
> @bdice why? While that makes the error go away, that assumes that any change in the fixture from one test is safe to persist to another. That _might_ be true, but I don't see why you would want to assume that when so many tests modify the fixture. Even if that's currently true, it would be easy to see adding one future tests that makes a nontrivial modification (e.g. changing the vertices of a shape since we've discussed making vertices settable) in a way that violates assumptions in another test.

I discussed with @vyasr offline and retract my suggestion. We wouldn’t want to allow tests to modify the value of the fixture and mess up other tests.

2021-01-14 16:11 UTC, bdice approved these changes
Looks good to me. I'll merge this so that the other approved PRs can be updated and merged.

2021-01-14 16:11 UTC, merged