Added new shape families for Archimedean, Catalan, Johnson, and other solids.
glotzerlab/coxeter pull request #177
Opened 2023-02-13 16:28 UTC by janbridley

## Description
Expanded on coxeter.families with methods and data for several families of common convex polyhedra:
* ``ArchimedeanFamily``: The 13 Archimedean solids.
* ``CatalanFamily``: The 13 Archimedean duals.
* ``JohnsonFamily``: The 92 Johnson solids.
* ``PrismAntiprismFamily``: The 16 n-gonal prisms and antiprisms ranging from n=3 to n=10.
* ``PyramidDipyramidFamily``: The 6 equilateral pyramids and dipyramids.

Each new family is queryable with ``get_shape("Shape Name")`` and returns a ``ConvexPolyhedron`` normalized to volume of 1, just as ``PlatonicFamily`` currently does. Vertex data for all new families is stored as a float64, and stored data for the current ``PlatonicFamily`` has been updated to match that precision. This change fixes intermittent bugs that arose from lack of numerical precision. New pytests have been added to verify the new families behave as expected. 

## Motivation and Context
Querying polyhedra other than Platonic solids could be relatively difficult. This release streamlines the process and allows for simple access to a greatly increased number of convex solids.

## Types of Changes
- [ ] Documentation update
- [x] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2023-02-23 06:19 UTC, vyasr requested changes
Some minor suggestions here, as well as a request to clean out miniball-related changes. Aside from that, is there anyone else in the group who could confirm the validity of the shape families themselves? I am not working with these currently and it would be good for someone who is to take a few minutes to spot check that the produced shapes are valid.

2023-02-23 06:19 UTC, vyasr commented on tests/conftest.py
> +    print(combinedids)
I assume this print can be removed now.

2023-02-23 06:19 UTC, vyasr commented on tests/conftest.py
> +def combine_marks(*marks):
This is neat! I'm kind of surprised that this doesn't already exist, or that I haven't had to implement it myself before.

2023-02-27 17:48 UTC, janbridley commented on tests/conftest.py
> +def combine_marks(*marks):
Thank you! It took a little bit to implement but I will definitely be holding onto this code for future projects.

2023-03-27 15:08 UTC, vyasr approved these changes
This PR LGTM now! For future reference, once you've addressed PR review changes you can re-request review by clicking on the button right next to the reviewer name in the Reviewers section on the top-right of the PR page.

2023-03-27 15:09 UTC, vyasr commented
@janbridley feel free to click the "Squash and merge" button when you're ready!

2023-03-27 15:12 UTC, janbridley commented on tests/conftest.py
> +_archimedean_shape_names = ArchimedeanFamily.data.keys()
Thanks for the feedback, and noted for next time!

2023-03-27 16:01 UTC, merged