Coxeter shapes are now compatible with Signac statepoints.
glotzerlab/coxeter pull request #186
Opened 2023-06-26 19:54 UTC by janbridley

Prior to this PR, `coxeter.shapes` classes were not json serializable. Because of this, they could not be used directly as a parameter in a [signac](https://docs.signac.io/en/latest/) state point. This PR enables the following:

```
import signac
from coxeter.families import PlatonicFamily

cube = PlatonicFamily.get_shape("Cube")

project = signac.init_project()

statepoint = dict(N=64, seed=1, vf=0.60, types=["cube"], poly=cube)

job = project.open_job(statepoint)
```

Once loaded into the statepoint, many shape attributes are accessible from the dict:
```
job.statepoint.poly.vertices
>>>[[-0.5, -0.5, -0.5],
    [-0.5, -0.5,  0.5],
    [-0.5,  0.5, -0.5],
    [-0.5,  0.5,  0.5],
    [ 0.5, -0.5, -0.5],
    [ 0.5, -0.5,  0.5],
    [ 0.5,  0.5, -0.5],
    [ 0.5,  0.5,  0.5]]

job.statepoint.poly.centroid
>>>[[0.0, 0.0, 0.0]]

job.statepoint.poly.gsd_shape_spec
>>>{'type': 'ConvexPolyhedron', 'vertices': [[-0.5, -0.5, -0.5], [-0.5, -0.5, 0.5], [-0.5, 0.5, -0.5], [-0.5, 0.5, 0.5], [0.5, -0.5, -0.5], [0.5, -0.5, 0.5], [0.5, 0.5, -0.5], [0.5, 0.5, 0.5]]}

```

All coxeter.shapes store their defining attributes (for example, radius for a Sphere and vertices for a ConvexPolyhedron). All shapes also store their `centroid` in the new dict, and 

## Description
* Added __dict__ special method
* Added _data method (where Signac loads data from)
* Added `__getitem__`, `__iter__`, `keys`, and `items` methods required for proper Signac function
* Added pytests

## Motivation and Context
Signac scripts using this new structure can better interface with molecular dynamics software, especially HOOMD. For example, [gsd-formatted](https://hoomd-blue.readthedocs.io/en/latest/tutorial/02-Logging/03-Storing-Particle-Shape.html) `type_shapes` can be added to a logger directly from the statepoint via `job.statepoint.poly.gsd_type_shapes`. Similarly, `hoomd.hpmc` integrators can be initialized from data stored within the `poly` object and a shape's `inertia_tensor` can be directly added to `particles.moment_inertia`.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [x] Breaking change<sup>1</sup>

<sup>1</sup>The change has the potential to break existing functionality. Users who rely on the default-generated __dict__ method may find keys have different names after this change. 

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2023-06-27 03:49 UTC, bdice requested changes
This deviates from the Python object model in a few key ways. I would hesitate to merge this without a significant design change. Perhaps discussing the intended use cases would help point towards a solution that aligns better with the Python object model while still being useful for serializing shapes for use in signac data spaces.

2023-06-27 03:49 UTC, bdice commented on coxeter/shapes/base_classes.py
> +    def __dict__(self):
Don’t use `__dict__` for this. I would recommend using another attribute/method name that is not reserved by the Python data model. Something like `to_dict(self)` or `as_dict(self)` or `serialize(self)`. The `object.__dict__` attribute is considered special and is reserved as a read-only attribute. https://docs.python.org/3/library/stdtypes.html#special-attributes

Additionally, be aware that serialization of shapes to JSON is lossy (float to string conversion).

2023-06-27 03:49 UTC, bdice commented on coxeter/shapes/base_classes.py
> +Mapping.register(Shape)
Is registration necessary here? I would prefer to see the class meet the ABC Mapping interface requirements to satisfy this implicitly, rather than explicitly stating “this is a Mapping” by fiat.

2023-06-27 03:49 UTC, bdice commented on coxeter/shapes/circle.py
> +            "inertia_tensor": self.inertia_tensor,
I would prefer to see shape serializations contain only the minimal amount of information needed to reconstruct the shape as an object. Coxeter should be used to compute an inertia tensor when it is needed, from the inputs to the class constructor.

2023-06-27 04:02 UTC, bdice commented
The GSD shape specification is almost exactly what I would recommend as a serialization format. Can you use the `gsd_shape_spec` attribute to serialize the shape as a dict, save that in the statepoint, and use `coxeter.from_gsd_type_shapes` to deserialize the dict into a shape for further computation? If there are shapes this doesn’t handle, we might be able to expand the GSD shape spec, but last I knew this should be sufficient.

2023-06-27 13:02 UTC, janbridley commented on coxeter/shapes/base_classes.py
> +    def __dict__(self):
Sounds good - thank you for the feedback on this, and I will look into a more specific (and nonreserved) method

2023-06-27 15:10 UTC, janbridley commented on coxeter/shapes/circle.py
> +            "inertia_tensor": self.inertia_tensor,
See [b1e5165](https://github.com/glotzerlab/coxeter/pull/186/commits/b1e51659a95cec39f696e1c4a3861883e2f03300)

2023-08-30 13:48 UTC, janbridley commented
This PR requires some thought into the best manner to approach this problem, and I do not believe it is particularly high priority right now. I have marked it as a draft to direct focus toward more important tasks.

2024-01-29 20:11 UTC, janbridley commented
I will reopen this issue as a new PR with significant changes to the internal implementation

2024-01-29 20:11 UTC, closed without merging