Performance rewrite of ConvexPolyhedron
glotzerlab/coxeter pull request #188
Opened 2023-08-08 14:09 UTC by janbridley

Prior to this PR, the ConvexPolyhedron class used Scipy's (Qhull) convex hull to compute faces of the solid. The shape was then initialized in the same manner as a standard Polyhedron. This rewrite stores simplices and other data from the convex hull, which can be used to accelerate many of the classes methods. Slow and commonly run functions have been rewritten for performance, and new and/or improved pytests have been written.

## Description
The new class builds a convex hull, then stores most of the data from that object. This data, especially the list of simplices, allow for numpy vectorization of many functions that required a for loop in the previous code. These simplices can be sorted to ensure math involving the curl/divergence theorems works properly, and can be merged based on common normals to build faces similar to the current merge_faces function. 

The following feature has been added:
* a Fast flag, set on ConvexPolyhedron creation. Defaults to false, but if manually set to true it will skip the slow sort_faces method and will not precompute coplanar simplices. These methods are called when needed, and checks are performed to ensure they are only run where required.

The following methods have been replaced or reimplemented, and a brief description is given:

* find_equations: vectorized using numpy
* _surface_triangulation: updated to use precalculated simplices, so polytri is not required
* volume, surface_area: reimplemented to use stored volume data for the calculations. 
* centroid: rewritten to calculate from a list of simplices. Vectorized using numpy. (_centroid_from_triangulated_surface)
* _compute_inertia_tensor: fully rewritten for performance, using an [algorithm](https://dl.acm.org/doi/10.1145/355873.355885) that works with tetrahedral decompositions that include negative-volume tetrahedra. It is also significantly faster.
* _rescale: updated to properly scale all stored properties. Also recalculates the centroid to ensure proper behavior.
* get_face_area: vectorized with numpy

The following new methods have also been added:

* _combine simplices (faster alternative to merge faces, but only works on simplices)
* _find_simplex_equations: similar to _find_equations, but works on every simplex rather than every face
* _find_coplanar_simplices: helper function that finds simplices with the same plane equation (within a tolerance). 
* _calculate_signed_volume: faster method of computing volume via a tetrahedral decomposition. Used as an internal check that volume is stable when modifying the shape
* _find_face_centroids: used with the new face_centroids property. Quickly finds the center of mass for each of the polygonal faces

The following properties have been added:
* simplices
* equations
* face_centroids

## Motivation and Context
Creation of a ConvexPolyhedron object takes tens of milliseconds - this is fine when generating small numbers of shapes, but can become a significant hindrance when generating tens or hundreds of thousands. In addition, many commonly used methods (especially volume, centroid, and inertia tensor) took on the order of milliseconds and did not cache their data. These changes address these performance issues, and add a wide range of private variables which can be used to more quickly calculate geometric properties that have not yet been implemented. Benchmarks will be included below but in general this rewrite provides a 10x-100x performance improvement on improved methods.

## Types of Changes

- [] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [-] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2023-08-09 14:15 UTC, janbridley commented
[0cf79cb](https://github.com/glotzerlab/coxeter/pull/188/commits/0cf79cb9b78ad40b6eaa4fe2cb02183fff490c40) is failing because it is dependent on #171 . Once that PR is merged, tests will pass

2023-08-16 20:20 UTC, bdice reviewed
This is a pretty significant change for the `ConvexPolyhedron` class. I'm happy to see you were able to make it faster, but there are a lot of design questions here (such as whether it is a good idea to add a flag like `fast=True` to the constructor, which makes this class behave quite differently than the rest of `coxeter`). Generally, `coxeter` was designed to provide a common framework for representing geometry classes (which we previously lacked in the Glotzer group), and speed was not the central goal. This design choice is reflected in its implementation (aiming for readability and simplicity of implementation over speed in most cases).

Unfortunately I don't have bandwidth to review this properly in the next 2 weeks. I'd encourage seeking reviews from other maintainers/users of the coxeter package.

2023-08-29 14:04 UTC, janbridley commented
> there are a lot of design questions here (such as whether it is a good idea to add a flag like fast=True to the constructor, which makes this class behave quite differently than  the rest of coxeter). Generally, coxeter was designed to provide a common framework for  representing geometry classes (which we previously lacked in the Glotzer group), and speed was not the central goal. This design choice is reflected in its implementation (aiming for readability and simplicity of implementation over speed in most cases).


Totally valid to not have the bandwidth this week - I looped in @DomFijan for this. 

In terms of the scope of coxeter and the differences in mindset between this code (and a few other recent PRs) as compared to the state of the package a year ago: coxeter was created as a common geometry framework, but it was not initially intended to be used beyond creating a few dozens of shapes at a time. However, the tools here are widely applicable and many glotzergroup members (and presumably a few other researchers) are using the package as a comprehensive computational geometry package. This includes use creating hundreds or thousands of shapes at a time, as well as using coxeter inside molecular dynamics scripts to easily compute shape properties. There is definitely a use case for faster algorithms, and I would argue that although simple iteration based code may be easier to read, the barrier to understanding reasonably optimized numpy code is not significantly higher than the alternative. Speed is not the primary purpose of coxeter, and I do not think it should be - but orders-of-magnitude performance improvements with no loss in accuracy are well worth the slight increase in complexity.


In terms of the `fast` flag in particular: although its effectiveness is somewhat limited in the current implementation, there are plans to support convex decompositions in the future which would benefit from being able to use some or all of the ConvexPolyhedron code without a large number of extra calculations being performed on each segment. That being said, I am fine removing the feature in this PR, as it is not particularly difficult to implement.

2023-09-27 19:22 UTC, janbridley commented
I have marked this PR as a draft temporarily, as there is a significant bug when creating a ConvexPolyhedron with a non-convex input set. A failure in this case is fairly reasonable, but the error should be (a) more predictable and (b) well-documented.

### Current behavior:
```python
>>> verts
array([[-0.5,  0.5, -0.5],
       [-0.5,  0.5,  0.5],
       [ 0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5],
       [ 0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5],
       [ 0.5,  0.5, -0.5],
       [ 0. ,  0. ,  0. ],
       [ 0.5, -0.5,  0.5]])
>>> coxeter.shapes.ConvexPolyhedron(verts)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/$USER/coxeter/coxeter/shapes/convex_polyhedron.py", line 114, in __init__
    self._sort_simplices()
  File "/Users/$USER/coxeter/coxeter/shapes/convex_polyhedron.py", line 205, in _sort_simplices
    vertices = self._vertices[self._simplices]
               ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: index 8 is out of bounds for axis 0 with size 8
```

When a non convex set is used as an input, vertices that don't contribute to the hull are removed from self._vertices. However - the _indices_ to those vertices stored in self._simplices are not updated, raising this error.

2023-10-23 15:42 UTC, janbridley commented
The class has been updated to raise a ValueError when a nonconvex set is provided. This error will also return a list of internal (or coplanar, degenerate, etc) points for easier debugging.

2023-10-24 19:45 UTC, DomFijan commented on tests/conftest.py
> +
You should remove the circle ci folder and file. You shouldnt need this code after that I think

2023-10-24 19:45 UTC, DomFijan commented on .circleci/config.yml
> +              ignore: /.*/
You should remove this whole file

2023-10-24 19:46 UTC, DomFijan commented on Credits.rst
Need changelog entries as well?

2023-10-24 19:48 UTC, DomFijan commented on Credits.rst
Make sure you have a breaking changes category with API breaking changes.

2023-10-24 19:49 UTC, janbridley commented on tests/conftest.py
> +
This code is used to check the CI environment (GitHub actions) for pytest, which I think is useful - it allows us to define separate test behavior depending on the environment. There is probably a way to do this through GitHub actions with pytest marks, which I can look into if we want.

2023-10-24 19:49 UTC, janbridley commented on tests/conftest.py
> +
This code is used to check the CI environment (GitHub actions) for pytest, which I think is useful - it allows us to define separate test behavior depending on the environment. There is probably a way to do this through GitHub actions with pytest marks, which I can look into if we want.

2023-11-08 18:59 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +    properties that can be used to characterize geometric features of the polyhedron.
These lines are slightly too long. They should be shorter than 80 characters I
think. At least most of the old docstrings are shorter than 80 chars.

2023-11-08 19:02 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +        del self._convex_hull
Not sure if this logic makes sense. Wouldn't it be better to just pass
the convex hull to this function in the first place instead of first
assigninig it to `self._convex_hull` and deleting it after you are done
using it?

2023-11-08 19:04 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    properties that can be used to characterize geometric features of the polyhedron.
I believe our black config is set to a line length of 88, but I can adjust the docstrings to meet the tighter spec.

2023-11-08 19:04 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +        del self._convex_hull
That is a much cleaner idea, thank you!

2023-11-08 19:05 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +    def _combine_simplices(self, rounding: int = 15):
I'm not a huge fan of giving rounding as an int. I'd strongly advocate
this be passed as the actual precision we are looking to use ie. 1e-15
in this case.

2023-11-08 19:08 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +        del self._convex_hull
See [571d5b](https://github.com/glotzerlab/coxeter/pull/188/commits/571d5b51f37844eb5def545aa71285f91b24bf88)

2023-11-08 19:09 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +
These 3 functions have decently complicated logic and seem to be
important for a lot of the functionality of the class down the line.
Could you add a couple of tests for these? In case things break down it
would be very helpful to know where things fail. Especially if this is
not to time consuming to do. If coming up with tests is super hard maybe
its ok to leave without testing.

2023-11-08 19:11 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +
I will do some thinking about it - the sorting isn't simple, but it should be testable at least for known cases.

2023-11-08 19:34 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +    def _find_coplanar_simplices(self, rounding: int = 15):
According to SciPy docs the qhull object already contains coplanar
indices in .coplanar? Is there a reason why you don't use that? See:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html

2023-11-08 19:34 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +        """Reorder simplices counterclockwise relatative to the plane they lie on.
```suggestion
        """Reorder simplices counterclockwise relative to the plane they lie on.
```

2023-11-08 19:38 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +        angles = np.mod(angles - angles[0], 2 * np.pi)
Is this necessary? This just changes which vertex you start at basically
right? I might be missing something. arctan2 codomain is -pi to pi.

2023-11-08 19:53 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +        return np.arccos(np.dot(-n1, n2))
Dihedral should be on the whole circle (0 to 2pi). arccos codomain is
[0,pi]. I think you want arctan2 here.

2023-11-08 19:53 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +        principal_moments, principal_axes = np.linalg.eigh(self.inertia_tensor)
If we dont use principal moments you can always do _ instead.

2023-11-08 19:58 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +    def get_face_area(self, face=None):
can we have some tests for this fn as well?

2023-11-08 19:59 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +    def _calculate_signed_volume(self):
Is it useful to have signed volume available to the user stored in a
variable? Or expose this function?

2023-11-08 20:03 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +        self._faces = sorted_faces
Would it maybe make sense for faces to be convexPolygon-s instead of
just array of vertices? There might be some comp overhead to creating
them though.

2023-11-08 20:04 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +        self._faces = sorted_faces
Also simplices.

2023-11-08 20:06 UTC, DomFijan requested changes
I've left some comments that we should discuss. Some methods are lacking tests that should be added. And some minor tweaks are suggested.

2023-11-10 15:30 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +        self._faces = sorted_faces
There is a pretty significant performance overhead to doing this - furthermore, much of the array math breaks down. This would be another good use case for a "collection of shapes" object, but I don't think it makes sense here

2023-11-10 15:33 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    def _calculate_signed_volume(self):
We could certainly expose the quantity if you think it is valuable! We already compute the quantity on initialization so that should be simple

2023-11-10 15:39 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +        return np.arccos(np.dot(-n1, n2))
`shapes/Polyhedron` currently uses arccos, which I copied here as the initial code had changes to the method. I can remove this function and fall back to the (identical) code from  the nonconvex class, but we should take a look at the implementation offline

2023-11-10 15:44 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    def _find_coplanar_simplices(self, rounding: int = 15):
Coplanar points in hull are not the contributors to coplanar simplices (as needed here). Rather, they are points that lie "on" a facet but cannot be triangulated due to numerical imprecision - for example, a point at [0,0,1-ε] on the face of a cube.

2023-11-10 15:56 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    def centroid(self, value):
Setting the centroid takes ~130μs for a cube, and about 200 μs for a larger shape (metabidiminished rhombicosidodecahedron, as above). If we can find a clean pythonic way to achieve this I think that's a great idea - I will do some research

2023-11-10 16:17 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +        angles = np.mod(angles - angles[0], 2 * np.pi)
Pytests for ConvexPolyhedron pass with or without the shift, but the current code mirrors the behavior of `shapes/_reorder_verts`. Removing the rescaling from ConvexPolygon causes the test `test_polygon.p::test_nonregular_convex_polygon_distance_to_surface_unit_area_ngon` to fail. It seems that reordering the vertices is somehow required to ensure the resulting polygon is simple. On a first glance I can't figure out why this would be the case, but I think we should explore further because the behavior is quite odd. This also highlights that we should add some 3D test cases with non regular faces - the current `named_solids_mark` does not include anything more irregular than Johnson solids

2023-11-10 16:20 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +        principal_moments, principal_axes = np.linalg.eigh(self.inertia_tensor)
See [9aa4a59](https://github.com/glotzerlab/coxeter/pull/188/commits/9aa4a59d2422f11edd8392d3ca036be33820a1bb)

2023-11-21 17:55 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    def _combine_simplices(self, rounding: int = 15):
Do you have any thoughts on how this could be implemented? My current approach hashes the plane equation which makes comparison-based approaches trickier. I could try and reimplement this in another way, but I have not found a non-hashing based approach that is comparable in performance.

2023-11-21 17:59 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    def centroid(self, value):
I think that this is somewhat similar to the "fast" flag - logging which values need to be updated when other properties are changed is a pretty major change, and should perhaps be left for its own PR (see #44)

2023-11-21 18:30 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    def get_face_area(self, face=None):
Working on it - I caught a bug so it will be a few

2023-12-04 17:29 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    def get_face_area(self, face=None):
[4fe9d88](https://github.com/glotzerlab/coxeter/pull/188/commits/4fe9d8846b26b755bc8adbdbb66828c49513404e) addresses issues with the `_find_coplanar_simplices` method that were causing errors with get_face_area. The new method takes a floating point tolerance (rather than an integer number of decimal places), and combines all of the logic into the `_combine_simplices` method, as there was significant overlap in functionality. This addresses several of the comments given above.

2023-12-21 01:33 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +    def _combine_simplices(self, rounding: int = 15):
I solved this in [4fe9d88](https://github.com/glotzerlab/coxeter/pull/188/commits/4fe9d8846b26b755bc8adbdbb66828c49513404e) - tolerances are now done to 2e-15, and floating point values can be provided

2023-12-21 02:40 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +
I would love to test this method directly, but worry that doing so would be complicated enough to warrant a separate PR. There are many unique solutions to sorting the simplices, and the results will depend on both the ConvexHull's initial simplex ordering and the ordering of the points of the input set.

However, the correct ordering is tested indirectly by computations of the centroid and intertia tensor. If the sorting is incorrect, those values will evaluate to nonsensical quantities and will be picked up by several tests: the monte carlo inertia tensor calculation and centroid setter tests should prove particularly good for this, although we have many tests for those properties.

The best solution would be to enumerate all possible orderings for a tetrahedron and/or octahedron and test against that, but for now I think we are safe to leave the method as-is.

2024-01-18 21:53 UTC, DomFijan commented on coxeter/shapes/convex_polyhedron.py
> +
@janbridley  is #211  related to this?

2024-01-18 21:59 UTC, janbridley commented on coxeter/shapes/convex_polyhedron.py
> +
They are unrelated - they are both artifacts of SciPy's `ConvexHull`, but result from different behaviors

2024-01-18 22:06 UTC, janbridley commented
@tcmoore3 Any other feedback? If not I will merge in the morning and start working on a release

2024-01-19 14:55 UTC, tcmoore3 approved these changes

2024-01-19 15:18 UTC, merged