Migrate CI to GitHub actions
glotzerlab/coxeter pull request #200
Opened 2023-09-19 19:45 UTC by DomFijan

Migration from Circle CI will involve removing Circle CI files and replacing them with github actions files. Additionally, dependabot integration will be added.
 
## Description
Swap testing with github actions. 
Swap PyPI uploading upon tagging to github CI.
Re-do the testing approach to be compatible with dependabot usage.

## Motivation and Context
Github actions > Circle CI ?

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2023-09-20 11:54 UTC, joaander requested changes
Thanks! I have suggestions for improvement.

2023-09-20 11:54 UTC, joaander commented on tests/requirements.txt
Separate requirements files that are for *users* and for *CI*. They are used under different scenarios. Requirements that will be used as part of solving environments are best with lower bounds only (see https://iscinumpy.dev/post/bound-version-constraints/) and upper bounds only in very controlled circumstances.

For *CI*, however, we want exact pins. With no pin, rerunning CI on the *same commit* can pass one day and fail the next due to upstream releases. Using exact pins mitigates this risk.

Dependabot will periodically issue pull requests to update the exact pins. In this way, you can ensure, one pull request at a time, that each new upstream dependency release passes tests (and any needed changes are made) before updating the pin. See https://github.com/glotzerlab/gsd/pull/281 for an example of a dependabot pull request.

I often put CI specific requirements files in the `.github` directory.

2023-09-20 11:54 UTC, joaander commented on .github/workflows/CI.yaml
> +    - uses: actions/checkout@v3
```suggestion
    - uses: actions/checkout@v4
```
Checkout is on v4 now. If you don't mind a few extra dependabot PRs, use `v4.0.0` to ensure repeatability.

2023-09-20 11:54 UTC, joaander commented on .github/workflows/CI.yaml
> +      uses: actions/setup-python@v4
```suggestion
      uses: actions/setup-python@v4.7.0
```
[optional] (see discussion above)

2023-09-20 11:54 UTC, joaander commented on .github/workflows/CI.yaml
> +      shell: bash -l {0}
```suggestion
```
Bash login shells are only needed for conda environments.

2023-09-20 11:54 UTC, joaander commented on .github/workflows/CI.yaml
> +      shell: bash -l {0}
```suggestion
```
Same here.

2023-09-20 11:54 UTC, joaander commented on .github/workflows/CI.yaml
> +        python -m pip install pytest
```suggestion
```
pytest is in the requirements file.

2023-09-20 11:54 UTC, joaander commented on .github/workflows/PublishPyPI.yaml
> +        python setup.py sdist
I thought `python setup.py <anything>` was deprecated and removed. I use the [build](https://pypi.org/project/build/) in gsd to make the sdist. I think it can construct the wheel needed for coxeter as well (can test locally to be sure).

2023-09-20 11:54 UTC, joaander commented on .github/workflows/PublishPyPI.yaml
> +        python -m twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*
PyPI recommends trustless publishing going forward: See https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/. The advantage is that you do not need per-repository secrets. The *disadvantage* is that you accept the risk that all packages trustless publishing might be hacked simultaneously by one security breach.

2023-09-20 11:54 UTC, joaander commented on .github/workflows/PublishPyPI.yaml
> +  push:
Test the wheel build step on pull requests as well. Skip the upload step when it is not a tag build (or upload to testpypi instead if desired). See gsd for an example: https://github.com/glotzerlab/gsd/blob/70f7c04349646dd997ae23a3f90aecfbb6590f65/.github/workflows/build_wheels.yml#L91-L97

2023-09-20 11:54 UTC, joaander commented on .github/workflows/PublishPyPI.yaml
> +      run: |
Use [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) instead of manual twine commands.

2023-09-20 20:40 UTC, DomFijan commented on .github/workflows/PublishPyPI.yaml
> +        python -m twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*
We discussed offline and decided to not use trustless publishing yet.

2023-09-20 20:45 UTC, janbridley commented on tests/requirements.txt
These changes should probably go in a .github/test-requirements.txt - otherwise, normal users who `pip install .[tests]` will get the pinned packages

2023-09-25 14:36 UTC, joaander approved these changes
Thanks!

2023-09-25 16:19 UTC, janbridley approved these changes

2023-09-26 22:45 UTC, merged