Switch linting to ruff
glotzerlab/coxeter pull request #203
Opened 2023-09-28 21:50 UTC by DomFijan

Flake8 is slow and sometimes doesn't play well with black.

## Description
Ruff is a replacement for flake8 and many other linters. It is fast. Also works on jupyter notebooks. It's supposed to play well with black?

## Motivation and Context
Modernize our linting setup.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2023-10-02 19:05 UTC, joaander requested changes
Thanks! I have some suggestions for improvement.

2023-10-02 19:05 UTC, joaander commented on pyproject.toml
> +  "D407", # dashed underline missing after section - should I enable this? many docs fail this
Looking at `setup.cfg` below, it appears that pydocstyle warnings were never enabled. Instead of ignoring all of these `D4*` warnings, consider updating the documentation to follow the numpy style convention that these check.

If there are some exceptional cases that you simply cannot document following the chosen convention, then use `noqa` to ignore those on a case by case basis: https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html#in-line-ignoring-errors

2023-10-03 19:06 UTC, janbridley commented on pyproject.toml
> +  "B904", # I think this one doesn't work as intended.
Has this been confirmed to work properly?

https://docs.astral.sh/ruff/rules/raise-without-from-inside-except/

2023-10-03 19:11 UTC, janbridley approved these changes

2023-10-03 19:31 UTC, joaander commented on pyproject.toml
> +  "B904", # I think this one doesn't work as intended.
Indeed, it would be good to raise chained exceptions. Can you give an example of a place where this warning triggers when it should not?

2023-10-03 20:03 UTC, DomFijan commented on pyproject.toml
> +  "B904", # I think this one doesn't work as intended.
It's complaining about the following two pieces of code, however according to [docs](https://docs.astral.sh/ruff/rules/raise-without-from-inside-except/) `if` should be inside `except` for this to be triggered:
[Code 1](https://github.com/glotzerlab/coxeter/blob/dcfc9f85d382d3182769de01e86a3a847dfa97f5/coxeter/shapes/base_classes.py#L182C1-L197C38):
```
            try:
                import importlib

                backend = importlib.import_module(f"plato.draw.{backend}")
            except ImportError:
                raise ImportError(
                    f"Backend plato.draw.{backend} could not be imported."
                )
            if scene_kwargs is None:
                scene_kwargs = {}
```
[Code 2](https://github.com/glotzerlab/coxeter/blob/dcfc9f85d382d3182769de01e86a3a847dfa97f5/coxeter/shapes/utils.py#L47C1-L60C55):
```
        try:
            import matplotlib.pyplot as plt
        except ImportError:
            raise ImportError("matplotlib must be installed for plotting.")
        fig = plt.figure()
        if not axes3d:
            ax = fig.subplots()
            ax.set_aspect("equal", "datalim")
        else:
            # This import registers the 3d projection
            from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

            ax = fig.add_subplot(111, projection="3d")
```
Thoughts?

2023-10-03 20:42 UTC, janbridley approved these changes

2023-10-04 13:21 UTC, joaander commented on pyproject.toml
> +  "B904", # I think this one doesn't work as intended.
Yes, you should:

```
except ImportError as exception:
    raise ImportError(...) from exception
````
The presence of the `if` in the documentation example is extraneous. Exception chaining is a good practice any time you raise from within an `except` block.

2023-10-04 13:28 UTC, joaander requested changes
On reviewing the two ignored bugbear checks, I think they are both good recommendations. Please remove the B* ignores and implement the recommended changes to the code.

2023-10-04 13:28 UTC, joaander commented on pyproject.toml
> +  "B028", # This forces usage of stack level in warnings.
You use `warnings.warn` in coxeter to warn about deprecated properties. I think the `stacklevel=2` option would be helpful for users and the recommendation in the docs is a good one: https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/. This will help users identify which line in *their* code is causing the warning.

2023-10-04 15:47 UTC, janbridley approved these changes

2023-10-04 20:17 UTC, janbridley commented
From `doc/development.rst`:

```
    Alternatively, the tools can be run manually using the commands:

  .. code-block:: bash

      black coxeter/ tests/
      isort coxeter/ tests/
```

Should we update this with commands to manually run ruff?

2023-10-04 20:49 UTC, janbridley commented on doc/source/development.rst
> +        ruff check . --fix
"Ruff's pre-commit hook should be placed after other formatting tools, such as Black and isort, unless you enable fixes, in which case, Ruff's pre-commit hook should run before Black, isort, and other formatting tools, as Ruff's fix behavior can output code changes that require reformatting."

2023-10-04 20:53 UTC, janbridley commented on doc/source/development.rst
> +        ruff check . --fix
[e40890f](https://github.com/glotzerlab/coxeter/pull/203/commits/e40890f6121d13b331c1bc6924cc33979ec0ce7a) should address this

2023-10-11 13:53 UTC, joaander approved these changes
This looks great, thanks!

2023-10-11 15:04 UTC, merged