Use uv in CI
glotzerlab/coxeter pull request #231
Opened 2024-07-08 19:53 UTC by janbridley

## Description

## Motivation and Context

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

2024-07-09 19:42 UTC, janbridley commented on .github/workflows/CI.yaml
> +    - uses: glotzerlab/workflows/setup-uv
```suggestion
    - uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049
```

2024-07-09 20:13 UTC, janbridley commented on .github/workflows/update_pipfiles.yaml
> +    - uses: glotzerlab/workflows/setup-uv
```suggestion
    - uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049
```

2024-07-10 12:19 UTC, joaander requested changes
Thanks! I have suggestions to improve this.

2024-07-10 12:19 UTC, joaander commented on .github/workflows/CI.yaml
> +    - uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049
```suggestion
    - uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049 # 0.2.0
      with:
        lockfile: ".github/requirements${{matrix.python-version}}.txt"
```
And delete the now duplicate "Set up Python environment" step.

2024-07-10 12:19 UTC, joaander commented on .github/workflows/CI.yaml
>          python -m pip install . --progress-bar off
```suggestion
        uv pip install . --no-build-isolation --no-deps -v
```
Install with the dependencies explicitly provided by the synced environment.

2024-07-10 12:19 UTC, joaander commented on .github/workflows/CI.yaml
> +        python -m pytest -v -n auto
Nice! So `pytest-xdist` was previously installed but not actually being used?

2024-07-10 13:22 UTC, janbridley commented on .github/workflows/CI.yaml
> +        python -m pytest -v -n auto
Looks like I was missing it actually! Somewhere along the way I forgot to commit the file.

2024-07-10 13:24 UTC, janbridley commented on .github/workflows/CI.yaml
> +    - uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049
This doesn't work in its current implementation because miniball doesn't have binaries. See [glotzerlab/workflows#8](https://github.com/glotzerlab/workflows/issues/8)

2024-07-10 14:15 UTC, janbridley commented on .github/workflows/CI.yaml
> +        uv pip install . --no-build-isolation --no-deps -v
```suggestion
        uv pip install . --no-build-isolation --no-deps --system -v
```

2024-07-10 16:27 UTC, janbridley commented on .github/workflows/CI.yaml
> +    - uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049
```suggestion
    - uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049 # 0.2.0
      with:
      	onlybinary: "false"
        lockfile: ".github/requirements${{matrix.python-version}}.txt"
```

2024-07-11 20:20 UTC, joaander approved these changes
This looks good now.

2024-07-11 20:20 UTC, joaander commented on .github/workflows/update_pipfiles.yaml
This looks right now. The "Run workflow" button does not appear in https://github.com/glotzerlab/coxeter/actions/workflows/update_pipfiles.yaml so I'm not sure how to test this.

2024-07-18 16:19 UTC, merged